name:                   Tests

on:                     pull_request

env:
  FORCE_COLOR:          1

jobs:
  rspec:
    name:               RSpec
    runs-on:            ubuntu-latest
    steps:
      - uses:           actions/checkout@v2
      - uses:           actions/setup-ruby@v1
        with:
          ruby-version: ">=2.7.x"
      - name:           Setup RSpec
        run:            gem install --no-document rspec
      - name:           RSpec Report
        run:            rspec --force-color --format documentation
